### ISSUE TITLE
some extra steps to help with this flow

### ISSUE THREAD

**Issue by JeanMertz** [wercker/workflows-kubernetes-demo#7]
Hey,

At Blendle, we created some helper steps that help us deploy services to Kubernetes, using Wercker. The flow is almost identical to this one, except that we use these three steps to make things a bit more easy/safe:

* [blendle/verify-quay-tag](https://github.com/blendle/wercker-step-verify-quay-tag)
* [blendle/publish-quay-tag](https://github.com/blendle/wercker-step-publish-quay-tag)
* [blendle/ktmpl](https://github.com/blendle/wercker-step-ktmpl)

Here's an example `deploy` pipeline:

```yaml
deploy:
  steps:
  - blendle/verify-quay-tag:
    token: $QUAY_API_TOKEN
    repository: blendle/app
    tag: $WERCKER_GIT_COMMIT

  - blendle/publish-quay-tag:
    token: $QUAY_API_TOKEN
    repository: blendle/app
    current: $WERCKER_GIT_COMMIT
    tag: latest
    if: $ENV
    eq: production

  - create-file:
    filename: ca.pem
    content: $KUBERNETES_CA_CERT
    hide-from-log: true

  - create-file:
    filename: admin.pem
    content: $KUBERNETES_CLIENT_CERT
    hide-from-log: true

  - create-file:
    filename: admin-key.pem
    content: $KUBERNETES_CLIENT_KEY
    hide-from-log: true

  - blendle/ktmpl:
    template: config/kubernetes.yml
    parameters: REPLICA_COUNT=$REPLICA_COUNT VERSION=$WERCKER_GIT_COMMIT ENV=$ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    base64_parameters: AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

  - kubectl:
    server: $KUBERNETES_ADDRESS
    certificate-authority: ca.pem
    client-certificate: admin.pem
    client-key: admin-key.pem
    raw_global_args: --namespace $ENV
    command: apply -f kubernetes.yml --record --validate
```

Just an FYI, they might be interested to others as well.
